#!/usr/bin/env bash
# Initialize a counter variable
counter=0

# Loop until the counter reaches 10
until [ $counter -eq 10 ]
do
  # Display "Best School"
  echo "Best School"
  
  # Increment the counter
  ((counter++))
done