#!/usr/bin/env bash
# Initialize counter
counter=1

# Loop through numbers 1 to 20
while [ $counter -le 20 ]; do
    # Use case statement to check the current iteration number
    case $counter in
        4)
            echo "4"
            echo "Bad luck from China"
            ;;
        9)
            echo "9"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "Bad luck from Italy"
            ;;
        *)
            # For other numbers, just display the number
            echo "$counter"
            ;;
    esac

    # Increment counter
    ((counter++))
done
